# Generated by Django 5.2.8 on 2025-11-16 08:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('platform', models.CharField(choices=[('mobile', 'Mobile'), ('pc', 'PC'), ('webgame', 'Webgame'), ('console', 'Console')], default='mobile', max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('region', models.CharField(default='Global', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameProductDiamond',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diamond_quantity', models.PositiveIntegerField(help_text='Number of diamonds (e.g., 100, 210, 310)', unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., '100 Diamonds')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diamonds/')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price before discount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', help_text='Currency code (e.g., BDT, USD)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock_quantity', models.PositiveIntegerField(default=9999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['diamond_quantity'],
            },
        ),
        migrations.CreateModel(
            name='GameProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('currency', models.CharField(default='BDT', help_text='Currency code (e.g., BDT, USD)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.game')),
                ('available_diamonds', models.ManyToManyField(blank=True, help_text='Select which diamond products are available for this game product', related_name='game_products', to='products.gameproductdiamond')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameProductDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_product_diamond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.gameproductdiamond')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('game_product_diamond', 'discount_percentage')},
            },
        ),
        migrations.CreateModel(
            name='GameProductTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('in_game_player_id', models.CharField(help_text='Player ID / Account ID for the game', max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game_server', models.CharField(blank=True, max_length=100)),
                ('game_region', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(choices=[('bkash', 'Bkash')], default='bkash', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('save_for_future', models.BooleanField(default=False, help_text='Save player ID for future purchases')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.gameproduct')),
                ('game_product_diamond', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.gameproductdiamond')),
                ('game_product_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='products.gameproductdiscount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='products_ga_user_id_d2ba24_idx'), models.Index(fields=['status', '-created_at'], name='products_ga_status_3c6ec3_idx'), models.Index(fields=['transaction_id'], name='products_ga_transac_c708bd_idx'), models.Index(fields=['in_game_player_id'], name='products_ga_in_game_43f36a_idx')],
            },
        ),
    ]
